dateModified: 1740885533
email:
  fromEmail: sergiopgomes92@gmail.com
  fromName: my-craft
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    96e50e63-9a88-4597-8d71-274e23fe7f45: my-craft # my-craft
    596cdf8a-7158-4f0c-8071-20c3e4a72604: my-craft # my-craft
system:
  edition: solo
  live: true
  name: my-craft
  schemaVersion: 5.6.0.2
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
